package order

import (
	"context"
	"time"
)

// Attr is a single selected attribute on an order, ready to be persisted as a
// row in the order_attrs table.
type Attr struct {
	Name  string // rendered attribute title, e.g. "Display color"
	Value string // rendered value title, e.g. "Red"
	Price int    // per-attribute add-on price in minor units (e.g. cents)
}

// Order is a customer order ready to be persisted.
//
// Fields generated by the database (id, status, timestamps) are intentionally
// absent: the writer relies on column defaults.
type Order struct {
	ProductID    string
	Email        string
	Price        int // total in minor units: base price + sum of Attr.Price
	Currency     string
	FirstName    string
	MiddleName   string
	LastName     string
	Country      string
	City         string
	Phone        string
	Address      string
	Attrs        []Attr // sorted by attribute key for deterministic ordering
	CustomerNote string
}

// HistoryEntry is one row of an order's status timeline.
type HistoryEntry struct {
	ID        string
	Status    string
	Note      *string // nil when SQL NULL
	CreatedAt time.Time
}

// Record is a fully-populated order read from the store, including DB-generated
// fields and all related attrs and history entries.
type Record struct {
	ID           string
	ProductID    string
	Status       string // order_status enum, as text
	Email        string
	Price        int
	Currency     string
	FirstName    string
	MiddleName   *string // nil when SQL NULL
	LastName     string
	Country      string
	City         string
	Phone        string
	Address      string
	AdminNote    *string // nil when SQL NULL
	CustomerNote *string // nil when SQL NULL
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Attrs        []Attr         // never nil; possibly empty
	History      []HistoryEntry // chronological, oldest first; never nil
}

// Writer persists an order to a backing store.
type Writer interface {
	Write(ctx context.Context, o Order) error
}

// Reader reads orders from a backing store.
type Reader interface {
	List(ctx context.Context) ([]Record, error)
}

// Service submits orders via a Writer and reads them via a Reader.
type Service struct {
	w Writer
	r Reader
}

// NewService returns a Service backed by w and r.
func NewService(w Writer, r Reader) *Service {
	return &Service{w: w, r: r}
}

// Submit writes the order to the backing store.
func (s *Service) Submit(ctx context.Context, o Order) error {
	return s.w.Write(ctx, o)
}

// List returns all orders, newest first. Always returns a non-nil slice on
// success (possibly empty).
func (s *Service) List(ctx context.Context) ([]Record, error) {
	return s.r.List(ctx)
}
