package order

import (
	"context"
	"encoding/json"
	"errors"
	"time"
)

// Invoice status enum values, kept in sync with the invoice_status PostgreSQL
// enum. The webhook handler maps provider-specific status strings (e.g.
// Monobank's "success"/"failure") onto these values.
const (
	InvoiceStatusProcessing = "processing"
	InvoiceStatusHold       = "hold"
	InvoiceStatusPaid       = "paid"
	InvoiceStatusFailed     = "failed"
	InvoiceStatusReversed   = "reversed"
)

// ErrNotFound is returned by Reader implementations when the requested
// order does not exist.
var ErrNotFound = errors.New("order not found")

// ErrTransitionNotAllowed is returned by Service.UpdateStatus and the
// underlying OperatorWriter when the requested target status is not a legal
// next step from the order's current status. The handler maps it to 409.
var ErrTransitionNotAllowed = errors.New("transition not allowed")

// Attr is a single selected attribute on an order, ready to be persisted as a
// row in the order_attrs table.
type Attr struct {
	Name  string // rendered attribute title, e.g. "Display color"
	Value string // rendered value title, e.g. "Red"
	Price int    // per-attribute add-on price in minor units (e.g. cents)
}

// Invoice is the result of issuing a payment invoice with a provider, ready
// to be persisted into order_invoices.
type Invoice struct {
	Provider string // e.g. "monobank"
	ID       string // provider's invoice id; stored in the row's primary key
	PageURL  string // hosted payment page URL
	Amount   int    // minor units, mirrors the order total at issue time
	Currency string // alpha-3 (e.g. "UAH")
}

// NotificationEvent is a single status-change notification dispatched by Service
// to an optional Notifier after a successful order_history insert. Status holds
// the new order_status as text; Note is optional human-readable context (e.g.
// the rendered Monobank webhook note for a payment transition).
type NotificationEvent struct {
	OrderID        string
	Status         string
	Note           string
	TrackingNumber string // populated only on the "shipped" event from Service.UpdateStatus
}

// Notifier is the consumer side of NotificationEvent. Implementations must be
// non-blocking and best-effort: a failure to deliver a notification must never
// surface to the caller. Service.Submit, AttachInvoice and RecordInvoiceEvent
// invoke Notify synchronously after the underlying transaction commits, so any
// blocking or slow Notify implementation will couple the notifier's latency to
// request hot paths. Concrete implementations should hand off to a background
// worker.
type Notifier interface {
	Notify(ctx context.Context, evt NotificationEvent)
}

// Order is a customer order ready to be persisted.
//
// Fields generated by the database (id, status, timestamps) are intentionally
// absent: the writer relies on column defaults.
type Order struct {
	ProductID    string
	Email        string
	Price        int // total in minor units: base price + sum of Attr.Price
	Currency     string
	Lang         string // checkout language code (e.g. "en", "uk"), persisted on the order
	FirstName    string
	MiddleName   string
	LastName     string
	Country      string
	City         string
	Phone        string
	Address      string
	Attrs        []Attr // sorted by attribute key for deterministic ordering
	CustomerNote string
}

// HistoryEntry is one row of an order's status timeline.
type HistoryEntry struct {
	ID        string
	Status    string
	Note      *string // nil when SQL NULL
	CreatedAt time.Time
}

// InvoiceEvent is one provider-side event for an invoice (typically a
// webhook delivery). It is the input to RecordInvoiceEvent. The persisted
// timeline is later used to derive the order's payment status.
type InvoiceEvent struct {
	OrderID   string
	InvoiceID string
	Provider  string          // e.g. "monobank"
	Status    string          // one of the InvoiceStatus* constants
	Note      string          // human-readable summary (rendered by the caller)
	Payload   json.RawMessage // verbatim provider payload, persisted as JSONB
	EventAt   time.Time       // provider's modifiedDate / event timestamp
}

// Record is a fully-populated order read from the store, including DB-generated
// fields and all related attrs and history entries.
type Record struct {
	ID           string
	ProductID    string
	Status       string // order_status enum, as text
	Email        string
	Price        int
	Currency     string
	Lang         string // checkout language code persisted at order creation
	FirstName    string
	MiddleName   *string // nil when SQL NULL
	LastName     string
	Country      string
	City         string
	Phone        string
	Address      string
	AdminNote      *string         `json:",omitempty"`
	CustomerNote   *string         `json:",omitempty"`
	TrackingNumber *string         `json:"tracking_number,omitempty"`
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Attrs        []Attr         // never nil; possibly empty
	History      []HistoryEntry // chronological, oldest first; never nil
	Invoices     []Invoice      // never nil; possibly empty
}

// Writer persists an order to a backing store and returns the assigned id.
type Writer interface {
	Write(ctx context.Context, o Order) (string, error)
}

// Reader reads orders from a backing store.
type Reader interface {
	// List returns all orders, newest first. When statuses is non-empty, only
	// orders whose order_status matches one of the supplied values are returned.
	// A nil or empty statuses slice means "no filter — return everything".
	//
	// Caller validates each value against the order_status enum (in production
	// this happens upstream in the OpenAPI request validator). An invalid
	// value reaches the SQL layer as an enum cast failure surfaced to the
	// handler as a generic 502 — no enum-specific error type is returned.
	List(ctx context.Context, statuses []string) ([]Record, error)
	// GetByID returns the fully-populated Record for the given order id.
	// Returns ErrNotFound when no row matches.
	GetByID(ctx context.Context, orderID string) (*Record, error)
	// GetStatus returns the current order_status (as text) for the given
	// order id. Returns ErrNotFound when no row matches.
	GetStatus(ctx context.Context, orderID string) (string, error)
}

// InvoiceWriter records an issued payment invoice for an order. Implementations
// run the inserts that transition the order to status='awaiting_payment' in a
// single transaction so the schema invariant "order has invoice ↔ status is
// awaiting_payment" cannot be violated by a partial write.
type InvoiceWriter interface {
	AttachInvoice(ctx context.Context, orderID string, inv Invoice) error
}

// InvoiceEventWriter persists a provider-side invoice event and, in the same
// transaction, recomputes the order's payment status from the latest event in
// the invoice timeline (ordered by EventAt). When the latest event implies a
// forward order_status transition, the order row and order_history are
// updated; otherwise the row is recorded but the order is left untouched.
//
// Returns the resolved order_status (as text) when a forward transition was
// applied, or "" when no transition fired (lifecycle decided not to apply,
// duplicate webhook dedupe, or the no-row-survived edge case).
//
// Inserting an event with the same (InvoiceID, Provider, Status, EventAt) as
// an existing row is a silent no-op (idempotent webhook replay).
type InvoiceEventWriter interface {
	RecordInvoiceEvent(ctx context.Context, evt InvoiceEvent) (string, error)
}

// OperatorWriter applies an operator-driven status transition to an order in
// a single transaction: SELECT … FOR UPDATE on the row, re-check the lifecycle
// rule, UPDATE orders (status + tracking_number when supplied), INSERT into
// order_history.
//
// applied is true iff the writer performed the UPDATE + INSERT. applied=false
// with a nil error means the order was already at target under the lock
// (concurrent same-target write); the caller MUST NOT dispatch a notification
// in that case.
type OperatorWriter interface {
	UpdateStatusByOperator(
		ctx context.Context,
		orderID, target, note, trackingNumber string,
	) (applied bool, err error)
}

// Service submits orders via a Writer, attaches invoices via an InvoiceWriter,
// reads them via a Reader, applies operator-driven status transitions via an
// OperatorWriter, and dispatches NotificationEvent on each successful
// order_history insert via an optional Notifier (nil disables notifications).
type Service struct {
	w   Writer
	r   Reader
	iw  InvoiceWriter
	iew InvoiceEventWriter
	ow  OperatorWriter
	n   Notifier
}

// NewService returns a Service backed by w, r, iw, iew, ow, and an optional
// notifier. Pass nil for n to disable notifications.
func NewService(
	w Writer, r Reader,
	iw InvoiceWriter, iew InvoiceEventWriter,
	ow OperatorWriter,
	n Notifier,
) *Service {
	return &Service{w: w, r: r, iw: iw, iew: iew, ow: ow, n: n}
}

// Submit writes the order to the backing store and returns the assigned id.
// On success, dispatches a NotificationEvent with status "new".
func (s *Service) Submit(ctx context.Context, o Order) (string, error) {
	id, err := s.w.Write(ctx, o)
	if err != nil {
		return "", err
	}
	if s.n != nil {
		s.n.Notify(ctx, NotificationEvent{OrderID: id, Status: "new"})
	}
	return id, nil
}

// AttachInvoice records an issued payment invoice for the given order. On
// success, dispatches a NotificationEvent with status "awaiting_payment".
func (s *Service) AttachInvoice(ctx context.Context, orderID string, inv Invoice) error {
	if err := s.iw.AttachInvoice(ctx, orderID, inv); err != nil {
		return err
	}
	if s.n != nil {
		s.n.Notify(ctx, NotificationEvent{OrderID: orderID, Status: "awaiting_payment"})
	}
	return nil
}

// List returns all orders, newest first. When statuses is non-empty, only
// orders whose order_status matches one of the supplied values are returned.
// nil or empty statuses returns all orders.
func (s *Service) List(ctx context.Context, statuses []string) ([]Record, error) {
	return s.r.List(ctx, statuses)
}

// GetStatus returns the current order_status for orderID. Returns ErrNotFound
// when no row matches.
func (s *Service) GetStatus(ctx context.Context, orderID string) (string, error) {
	return s.r.GetStatus(ctx, orderID)
}

// RecordInvoiceEvent persists a provider-side invoice event and recomputes
// the order's payment status. When the underlying writer reports a forward
// transition was applied (non-empty new status), dispatches a
// NotificationEvent carrying the new status and the event's note.
func (s *Service) RecordInvoiceEvent(ctx context.Context, evt InvoiceEvent) error {
	newStatus, err := s.iew.RecordInvoiceEvent(ctx, evt)
	if err != nil {
		return err
	}
	if s.n != nil && newStatus != "" {
		s.n.Notify(ctx, NotificationEvent{OrderID: evt.OrderID, Status: newStatus, Note: evt.Note})
	}
	return nil
}

// UpdateStatus applies an operator-driven status transition to an order. The
// caller is expected to validate at the request layer that target is one of
// the operator-permitted statuses and that trackingNumber is supplied iff
// target == "shipped".
//
// Flow:
//
//  1. Look up the current status (no lock). ErrNotFound is propagated.
//  2. If current == target, return (false, nil) — idempotent no-op, no DB
//     write, no notification.
//  3. If !ShouldApplyOperatorTransition(current, target), return
//     (false, ErrTransitionNotAllowed). No DB write, no notification.
//  4. Call the OperatorWriter, which re-checks the rule under the lock.
//     applied=false with nil error means a concurrent same-target writer beat
//     us; in that case no notification is dispatched.
//  5. On a real apply, dispatch NotificationEvent. TrackingNumber is set on
//     the event only when target == "shipped".
func (s *Service) UpdateStatus(
	ctx context.Context,
	orderID string,
	target string,
	note string,
	trackingNumber string,
) (bool, error) {
	current, err := s.r.GetStatus(ctx, orderID)
	if err != nil {
		return false, err
	}
	if current == target {
		return false, nil
	}
	if !ShouldApplyOperatorTransition(current, target) {
		return false, ErrTransitionNotAllowed
	}
	applied, err := s.ow.UpdateStatusByOperator(ctx, orderID, target, note, trackingNumber)
	if err != nil {
		return false, err
	}
	if applied && s.n != nil {
		evt := NotificationEvent{OrderID: orderID, Status: target, Note: note}
		if target == "shipped" {
			evt.TrackingNumber = trackingNumber
		}
		s.n.Notify(ctx, evt)
	}
	return applied, nil
}
