package order

import (
	"context"
)

// Attr is a single selected attribute on an order, ready to be persisted as a
// row in the order_attrs table.
type Attr struct {
	Name  string // rendered attribute title, e.g. "Display color"
	Value string // rendered value title, e.g. "Red"
	Price int    // per-attribute add-on price in minor units (e.g. cents)
}

// Order is a customer order ready to be persisted.
//
// Fields generated by the database (id, status, timestamps) are intentionally
// absent: the writer relies on column defaults.
type Order struct {
	ProductID    string
	Email        string
	Price        int // total in minor units: base price + sum of Attr.Price
	Currency     string
	FirstName    string
	MiddleName   string
	LastName     string
	Country      string
	City         string
	Phone        string
	Address      string
	Attrs        []Attr // sorted by attribute key for deterministic ordering
	CustomerNote string
}

// Writer persists an order to a backing store.
type Writer interface {
	Write(ctx context.Context, o Order) error
}

// Service submits orders via a Writer.
type Service struct {
	w Writer
}

// NewService returns a Service backed by w.
func NewService(w Writer) *Service {
	return &Service{w: w}
}

// Submit writes the order to the backing store.
func (s *Service) Submit(ctx context.Context, o Order) error {
	return s.w.Write(ctx, o)
}
